### ISSUE TITLE
Photo sphere not working.

### ISSUE THREAD

**Issue by mdshafiqulislamshamim** [Arnova8G2/Gcam_8.7.250.44#7]
---- Crash log ----

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object referenceat bdg.Q(PG:2)at ejy.P(PG:1)at ejy.H(PG:12)at ejy.p(PG:4)at cbf.q(PG:1)at hsn.h(PG:26)at hto.h(PG:3)at fwu.onClick(PG:12)at android.view.View.performClick(View.java:7743)at android.view.View.performClickInternal(View.java:7720)at android.view.View.access$3700(View.java:854)at android.view.View$PerformClick.run(View.java:29111)at android.os.Handler.handleCallback(Handler.java:938)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:210)at android.os.Looper.loop(Looper.java:299)at android.app.ActivityThread.main(ActivityThread.java:8309)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
---- Device Info ----
 - Brand : Redmi
 - Model : 220333QAG
 - Manufacturer : Xiaomi
 - Device : fog
 - Os version : Android 12 - 4.19.157-perf-g85e27949fb09
---- Gcam Mod Info ----
 - PackageName : com.google.android.GoogleCamera
 - VersionName : 8.7.250.build-8.0Beta4Fix.230325.2313

**Comment by Arnova8G2** [comment]
It's a bug from AUX mode, I have same bug on this package name

**Comment by mdshafiqulislamshamim** [comment]
But sir, this crash is from when i tap on photo sphere mode from more modes mode.

**Comment by mdshafiqulislamshamim** [comment]
But sir, this crash is from when i tap on photo sphere mode from more modes mode. https://user-images.githubusercontent.com/90249842/227781198-4d3879b0-0254-458d-b637-026117530300.mp4

**Comment by mdshafiqulislamshamim** [comment]
But sir, this crash is from when i tap on photo sphere mode from modes mode. https://user-images.githubusercontent.com/90249842/227781198-4d3879b0-0254-458d-b637-026117530300.mp4

**Comment by Arnova8G2** [comment]
yes same, I checked on Oneplus 8 Pro with google camera package it does this bug and uses AUX, on arn package no aux but photosphere works very well, I will replace photosphere's getCameraIdList with ID Back, front only.

**Comment by mdshafiqulislamshamim** [comment]
But sir, this crash is from when i tap on photo sphere mode from modes mode. https://user-images.githubusercontent.com/90249842/227781198-4d3879b0-0254-458d-b637-026117530300.mp4

   Okay sir. Let me test

**Comment by mdshafiqulislamshamim** [comment]
> yes same, I checked on Oneplus 8 Pro with google camera package it does this bug and uses AUX, on arn package no aux but photosphere works very well, I will replace photosphere's getCameraIdList with ID Back, front only.

Okay sir let me test

**Comment by mdshafiqulislamshamim** [comment]
Sir, it's really a bug of os. It works for few devices and doesn't work for few devices. The crash log that i am getting is also complicated.
